# ä¾§è¾¹æ èœå•
menu:
  HOME: /
  ABOUT: /about
  ARCHIVE: /archives
  CATEGORIES: /categories
  TAGS: /tags

# ç«™ç‚¹æ¬¡æ ‡é¢˜å’Œæ‰“å­—åŠ¨æ•ˆ
# https://github.com/mattboldt/typed.js
subtitle:
  enable: true # æ˜¯å¦å¼€å¯åŠ¨æ•ˆ
  text: welcome to my blog. # æ»šåŠ¨æ’­æ”¾ï¼Œå¦‚æœä¸éœ€è¦å¯ä»¥ç•™ç©º
  text3: # æœ€å¤šæ”¯æŒä¸‰æ®µæ–‡å­—
  startDelay: 0 # å»¶è¿Ÿæ—¶é—´
  typeSpeed: 200 # æ‰“å­—é€Ÿåº¦
  loop: true # æ˜¯å¦å¾ªç¯
  backSpeed: 100 # å›é€€é€Ÿåº¦
  showCursor: true # æ˜¯å¦æ˜¾ç¤ºå…‰æ ‡

# ç½‘ç«™å›¾æ ‡å’Œä¾§è¾¹æ logo
favicon: /images/favicon.ico
  # small: images/favicon-16x16.png
  # medium: images/favicon-32x32.png
  # apple_touch_icon: images/apple-touch-icon.png
  # safari_pinned_tab:
  # android_manifest: images/manifest.json
  # ms_browserconfig: images/browserconfig.xml
logo: /images/android-chrome-512x512.png

# å°é¢é…ç½®
# enable-æ˜¯å¦å¯ç”¨å°é¢ï¼›path-å°é¢èƒŒæ™¯å›¾ï¼›logo-å°é¢logo
cover:
  enable: true
  path: https://images.unsplash.com/photo-1555099962-4199c345e5dd?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80 # /images/code-picture-faded.jfif # /source/imagesç›®å½•ä¸‹é™„é€å¤šå¼ ç¾å›¾ï¼Œå¯æ›´æ¢
  logo: false #/images/ayer.svgï¼Œå¦‚æœä¸è¦ç›´æ¥è®¾ç½®æˆfalse

# é¡µé¢é¡¶éƒ¨è¿›åº¦æ¡
progressBar: true

# å‘Šç¤ºæ¿æ¨¡å—
broadcast:
  enable: false # trueå¼€å¯ï¼Œfalseå…³é—­
  type: 2 # 1ï¼šè‡ªå®šä¹‰è¾“å…¥ï¼Œ2ï¼šä¸€è¨€api(https://hitokoto.cn/)
  text: ä¸€ä¸ªå®‰é™ä¼˜é›…çš„hexoä¸»é¢˜ï¼Œå¿«é€Ÿä¸”å“åº”å¼ã€‚ # typeä¸º1æ—¶æœ‰æ•ˆ

# æ–‡ç« é…ç½®
# æ–‡ç« å¤ªé•¿ï¼Œæˆªæ–­æŒ‰é’®æ–‡å­—(åœ¨éœ€è¦æˆªæ–­çš„è¡Œå¢åŠ æ­¤æ ‡è®°ï¼š<!--more-->)
excerpt_link: Read More...
# å¦‚æœä½ å«Œæ¯ç¯‡æ–‡ç« æ‰‹åŠ¨åŠ moreæ ‡è®°æ¯”è¾ƒéº»çƒ¦ï¼Œåˆä¸æƒ³åœ¨é¦–é¡µå…¨æ–‡æ˜¾ç¤ºï¼Œå¯ä»¥æŠŠexcerpt_allè®¾ç½®æˆtrueï¼Œè¿™æ ·é¦–é¡µåªä¼šæ˜¾ç¤ºæ–‡ç« å½’æ¡£
excerpt_all: false

# æ˜¯å¦å¼€å¯ä»£ç å¤åˆ¶æŒ‰é’®
copy_btn: true
# æ˜¯å¦å¼€å¯æ–‡ç« åˆ†äº«æŒ‰é’®
share_enable: true
# å›½å†…çš„ç¤¾äº¤å¹³å°(If you are not in China, maybe you prefer to set:false)
share_china: false
# æ–‡ç« åˆ†äº«æ–‡å­—
share_text: Share

# åˆ†é¡µæ–‡å­—
nav_text:
  page_prev: Prev
  page_next: Next
  post_prev: Older
  post_next: Newer

# æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºç›®å½•
toc: true

# æ–‡ç« ä¸­çš„å›¾ç‰‡æ˜¯å¦æ”¯æŒç‚¹å‡»æ”¾å¤§
image_viewer: true

# https://github.com/willin/hexo-wordcount
# æ˜¯å¦å¼€å¯å­—æ•°ç»Ÿè®¡(å…³é—­è¯·è®¾ç½®enableä¸ºfalse)
# ä¹Ÿå¯ä»¥å•ç‹¬åœ¨mdæ–‡ä»¶é‡ŒFront-matterè®¾ç½®`no_word_count: true`å±æ€§ï¼Œæ¥è‡ªå®šä¹‰å…³é—­å­—æ•°ç»Ÿè®¡
word_count:
  enable: true
  # åªåœ¨æ–‡ç« è¯¦æƒ…æ˜¾ç¤º(ä¸åœ¨é¦–é¡µæ˜¾ç¤º)
  only_article_visit: true

# æ‰“èµ
# æ‰“èµtypeè®¾å®šï¼š0-å…³é—­æ‰“èµï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰reward:trueå±æ€§ï¼Œæ‰æœ‰æ‰“èµï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰æ‰“èµ
reward_type: 0
# æ‰“èµwording
reward_wording: "è¯·æˆ‘å–æ¯å’–å•¡å§~"
# æ”¯ä»˜å®äºŒç»´ç å›¾ç‰‡åœ°å€ï¼Œè·Ÿä½ è®¾ç½®logoçš„æ–¹å¼ä¸€æ ·ã€‚æ¯”å¦‚ï¼š/images/alipay.jpg
alipay: https://cdn.jsdelivr.net/gh/Shen-Yu/cdn/img/alipay.jpg
# å¾®ä¿¡äºŒç»´ç å›¾ç‰‡åœ°å€
weixin: https://cdn.jsdelivr.net/gh/Shen-Yu/cdn/img/wechat.jpg

# ç‰ˆæƒå£°æ˜
# ç‰ˆæƒå£°æ˜typeè®¾å®šï¼š0-å…³é—­ç‰ˆæƒå£°æ˜ï¼› 1-æ–‡ç« å¯¹åº”çš„mdæ–‡ä»¶é‡Œæœ‰copyright: trueå±æ€§ï¼Œæ‰æœ‰ç‰ˆæƒå£°æ˜ï¼› 2-æ‰€æœ‰æ–‡ç« å‡æœ‰ç‰ˆæƒå£°æ˜
copyright_type: 2

# æ˜¯å¦å¯ç”¨æœç´¢
# éœ€è¦å®‰è£…hexo-generator-searchdb(https://github.com/theme-next/hexo-generator-searchdb)
search: true

# RSSè®¢é˜…(å…ˆå®‰è£…hexo-generator-feedæ’ä»¶ï¼Œå†å»åšå®¢æ ¹ç›®å½•configè¿›è¡Œé…ç½®)
# ä¸æƒ³æ˜¾ç¤ºå¯ä»¥ç›´æ¥ç•™ç©º
rss: /atom.xml

# æ˜¯å¦å¯ç”¨é»‘å¤œæ¨¡å¼å¼€å…³
darkmode: true

# åŠ¨æ€èƒŒæ™¯æ•ˆæœ: 0-å…³é—­ï¼Œ1-åŠ¨æ€çº¿æ¡(è·Ÿéšé¼ æ ‡)
canvas_bg: 0

# è‡ªå®šä¹‰é¼ æ ‡æ ·å¼ï¼Œç›´æ¥æ›¿æ¢/images/mouse.curæ–‡ä»¶
mouse:
  enable: true
  path: /images/wand.cur

# é¼ æ ‡ç‚¹å‡»æ•ˆæœï¼š0-å…³é—­ï¼Œ1-çˆ±å¿ƒï¼Œ2-çˆ†ç‚¸çƒŸèŠ±ï¼Œ3-ç²’å­çƒŸèŠ±
click_effect: 0

# é¡µé¢å®½åº¦è‡ªå®šä¹‰ï¼ˆä¸å»ºè®®ä¿®æ”¹ï¼Œå¯èƒ½é€ æˆå¸ƒå±€æ··ä¹±ï¼‰ï¼Œarticle_widthæ–‡ç« å®½åº¦ï¼Œsidebar_widthä¾§è¾¹æ å®½åº¦
layout:
  article_width: 75rem
  sidebar_width: 12rem

# GitHub Ribbons-å°é¢å³ä¸Šè§’çš„forkmeï¼Œæ¢æ ·å¼ç›´æ¥åœ¨source/imagesç›®å½•ä¸‹æ›¿æ¢forkmeå›¾ç‰‡
github:
  # (å…³é—­è¯·è®¾ç½®ä¸ºfalse)
  enable: false
  url: https://github.com/Shen-Yu/hexo-theme-ayer

# ç½‘æ˜“äº‘éŸ³ä¹æ’ä»¶
music:
  enable: false
  # æ’­æ”¾å™¨å°ºå¯¸ç±»å‹(1ï¼šå°å°ºå¯¸ã€2ï¼šå¤§å°ºå¯¸)
  type: 1
  id: 22707008 # ç½‘æ˜“äº‘åˆ†äº«çš„éŸ³ä¹ID(æ›´æ¢éŸ³ä¹è¯·æ›´æ”¹æ­¤é…ç½®é¡¹)
  autoPlay: true # æ˜¯å¦å¼€å¯è‡ªåŠ¨æ’­æ”¾

# è®¿é—®é‡ç»Ÿè®¡(ä¸è’œå­)
busuanzi:
  enable: true

# å‹ç›Ÿcnzzç»Ÿè®¡(urlå¡«jsä»£ç srcé“¾æ¥)
cnzz:
  enable: true
  url: https://s9.cnzz.com/z_stat.php?id=1278069914&web_id=1278069914

# Google Analytics
google_analytics: ""
# ç™¾åº¦ç»Ÿè®¡
baidu_analytics: ""

# Mathjaxæ•°å­¦å…¬å¼
mathjax: false

# Katexæ•°å­¦å…¬å¼(allpostè®¾ç½®ä¸ºfalseæ—¶åªæœ‰å¤´éƒ¨è®¾ç½®math:trueçš„æ–‡ç« æ‰å¼€å¯)
# éœ€è¦æ›´æ¢hexoæ¸²æŸ“å™¨ï¼Œnpm un hexo-renderer-marked -S && npm i hexo-renderer-markdown-it-katex -S
katex:
  enable: false # true
  allpost: true
  copy_tex: false

# mermaidæµç¨‹å›¾ ä¸‰ä¸ªé€‰é¡¹ç¼ºä¸€ä¸å¯(https://mermaid-js.github.io/mermaid/)
mermaid:
  enable: false
  cdn: https://cdn.jsdelivr.net/npm/mermaid@8.9.2/dist/mermaid.min.js
  theme: forest

# ç½‘ç«™æˆç«‹å¹´ä»½(é»˜è®¤ä¸º 2019ï¼Œè‹¥å¡«å…¥å¹´ä»½å°äºå½“å‰å¹´ä»½ï¼Œåˆ™æ˜¾ç¤ºä¸º 2018-2019 ç±»ä¼¼çš„æ ¼å¼)
since: 2021

# ICPå¤‡æ¡ˆä¿¡æ¯å°¾éƒ¨æ˜¾ç¤º
icp:
  enable: false
  url: "http://www.beian.miit.gov.cn/" # å¤‡æ¡ˆé“¾æ¥
  text: "æµ™ICPå¤‡88888888" # å¤‡æ¡ˆä¿¡æ¯
# å…¬å®‰å¤‡æ¡ˆä¿¡æ¯å°¾éƒ¨æ˜¾ç¤º
gongan:
  enable: false
  img: /images/beian.png #å…¬å®‰å¤‡æ¡ˆå›¾ç‰‡
  url: "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=01234567890123" #å…¬å®‰å¤‡æ¡ˆé“¾æ¥
  text: "æµ™å…¬ç½‘å®‰å¤‡01234567890123å·" #å…¬å®‰å¤‡æ¡ˆä¿¡æ¯

# å‹æƒ…é“¾æ¥
friends_link:
  Ayerä¸»é¢˜: #ç½‘ç«™åç§°
    #ç½‘ç«™åœ°å€
    url: https://github.com/Shen-Yu/hexo-theme-ayer
    #ç½‘ç«™å›¾ç‰‡(å¯å¿½ç•¥ä¸å†™)
    img: /images/ayer.png
  GitHub:
    url: https://github.com/Shen-Yu
    img: https://cdn.jsdelivr.net/gh/Shen-Yu/cdn/img/github.png
  ç äº‘:
    url: https://gitee.com/shen-yu
    img: https://cdn.jsdelivr.net/gh/Shen-Yu/cdn/img/gitee.png
  Hexoå®˜ç½‘:
    url: https://hexo.io
    img: https://cdn.jsdelivr.net/gh/Shen-Yu/cdn/img/hexo.png
  Hexoå›¾è¡¨æ’ä»¶:
    url: https://github.com/Shen-Yu/hexo-tag-chart
    img: https://cdn.jsdelivr.net/gh/Shen-Yu/cdn/img/hexo-tag-chart.png

# è¯„è®ºï¼š1ã€Valine(æ¨è)ï¼›2ã€Gitalkï¼›3ã€Twikoo; 4.MiniValine

# 1ã€Valine[ä¸€æ¬¾å¿«é€Ÿã€ç®€æ´ä¸”é«˜æ•ˆçš„æ— åç«¯è¯„è®ºç³»ç»Ÿ](https://github.com/xCss/Valine)
# å¯ç”¨Valineå¿…é¡»å…ˆåˆ›å»ºleancloudåº”ç”¨ï¼Œ è·å– id|key å¡«å…¥å³å¯
leancloud:
  enable: false
  app_id: #
  app_key: #
# Valineé…ç½®
valine:
  enable: true # æ˜¯å¦å¯ç”¨
  avatar: monsterid # å¤´åƒæ ·å¼(https://valine.js.org/avatar.html)
  placeholder: ç»™æˆ‘çš„æ–‡ç« åŠ ç‚¹è¯„è®ºå§~ # placeholder

# 2ã€Gitalk(https://github.com/gitalk/gitalk)
gitalk:
  enable: false # true
  clientID: #client ID
  clientSecret: #client secret
  repo:  # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

# 3ã€Twikoo(https://github.com/imaegoo/twikoo)
twikoo:
  enable: false
  envId: #

# 4ã€MiniValine
# See: https://github.com/MiniValine/MiniValine
minivaline:
  enable: false
  # æ›´å¤šé€‰é¡¹ https://minivaline.js.org/docs/cn/#/Options æŒ‰ç…§ymlæ ¼å¼ç»§ç»­å¡«å†™å³å¯ ï¼ˆé™¤äº† [el] é€‰é¡¹ï¼‰
  # emoticonUrl ç­‰åˆ—è¡¨é€‰é¡¹ å¯å‚è€ƒ https://github.com/MiniValine/hexo-next-minivaline
  # ä¸‹é¢æ˜¯ä¸€ä¸ªä¾‹å­ï¼š
  serverURL: https://minivaline.your-domain.com

# 5 Utterances
utterances:
  enable: true
  repo: nina-dk/nina-dk.github.io
  issue_term: title
  label: ğŸ’¬ comment
  theme: github-light

# é¦–é¡µå¹¿å‘Šé…ç½®
# å¯ä»¥æ ¹æ®éœ€è¦è‡ªè¡Œå¢åŠ ad_3ï¼Œad_4...ï¼Œç•™ç©ºåˆ™ä¸æ˜¾ç¤ºï¼Œå»ºè®®å›¾ç‰‡å’Œurlä¸è¦å¸¦adç­‰å…³é”®è¯ï¼Œå¦åˆ™å¯èƒ½ä¼šè¢«adblockç­‰æ’ä»¶å±è”½
ads:
  ad_1:
    title: 
    img: 
    url:
    width:

# ç½‘ç«™å¼€å¯åŠ å¯†è®¿é—®ï¼Œå¯†ç å¯è®¾ç½®ä»»ä½•å­—ç¬¦
lock:
  enable: false
  password: 123456
